import UIKit

/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

var evenList: [Int] = []

var currentNumber: Int = 1
var previousNumber: Int = 1
var secondPreviousNumber: Int = 1

//Adds all number in the Fibonacci sequence whose values do not exceed four million to Array List.
while currentNumber < 4000000 {
    currentNumber = previousNumber + secondPreviousNumber
    
    if(currentNumber%2 == 0){
        evenList.append(currentNumber)
    }
    
    secondPreviousNumber = previousNumber
    previousNumber = currentNumber
}

//Even List
print(evenList)

//Sums up all the numbers inside the array.
print(evenList.reduce(0, +))
